kaudee-car/config/routes.rb
KaudeeCar::Application.routes.draw do
  get 'password_resets/new'

  namespace :api do
    namespace :v1 do
      resources :market
      resources :room
      resources :user
      resources :favorite
      resources :category
      resources :city
      resources :car
      resources :district
      resources :image
      resources :model
      get 'meta' => 'meta#index'
      post 'login' => 'login#index'
    end
  end
end

Rails.application.routes.draw do
  get 'password_resets/new'

  # You can have the root of your site routed with "root"
  root 'welcome#index'
  get 'map/list'
  get 'map/show'
  get 'map/new'
  get 'map/ios'
  get 'welcome/index'
  get 'welcome/policy' => 'welcome#policy'
  get 'welcome/test' => 'welcome#test'
  get 'password' => 'welcome#password'
  post 'login' => 'login#index'
  get 'signout' => 'login#signout'
  get 'market/enable' => 'market#enable'
  get 'market/disable' => 'market#disable'
  get 'admin' => 'user#admin'
  get 'geno' => 'user#geno'

  resources :market
  resources :room
  resources :user
  resources :car
  resources :favorite
  resources :image
  resources :category
  resources :district
  resources :city
  resources :brand
  resources :model
  resources :password_resets
end

kaudee-car/app/models/base.rb
class Base < ActiveRecord::Base
end

kaudee-car/app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :user
  has_many :favorite
end

kaudee-car/app/models/carbrand.rb
class Carbrand < ActiveRecord::Base
has_many  :carmodels
end

kaudee-car/app/models/carmodel.rb
class Carmodel < ActiveRecord::Base
end

kaudee-car/app/models/category.rb
class Category < ActiveRecord::Base
end

kaudee-car/app/models/city.rb
class City < ActiveRecord::Base
  has_many :districts
end

kaudee-car/app/models/district.rb
class District < ActiveRecord::Base
end

kaudee-car/app/models/favorite.rb
class Favorite < ActiveRecord::Base
 validates_uniqueness_of :user_id, :scope => :data_id
end

kaudee-car/app/models/image.rb
class Image < ActiveRecord::Base
	mount_uploader :img, ImageUploader
end

kaudee-car/app/models/market.rb
class Market < ActiveRecord::Base
  belongs_to :user
  has_many :favorite
  #mount_uploader :image, ImageUploader
end

kaudee-car/app/models/room.rb
class Room < ActiveRecord::Base
  #belongs_to :user
  #has_many :favorite
end

kaudee-car/app/models/user.rb
class User < ActiveRecord::Base
  before_create :generate_access_token

  has_many :markets
  validates :email, :password, presence: true
  validates_uniqueness_of :email

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end
  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  private

  def generate_access_token
    begin
      self.access_token = SecureRandom.hex
    end while self.class.exists?(access_token: access_token)
  end
end

kaudee-car/app/controllers/welcome_controller.rb
class WelcomeController < DefaultController
  #layout "application", except: [:policy, :password]

  def index
    @cars = Car.count
    @users = User.count
  end

  def policy
  end

  def password
  end

  def test
  end
end

kaudee-car/app/helpers/car_helper.rb
module CarHelper
end

kaudee-car/app/helpers/home_helper.rb
module HomeHelper
end

kaudee-car/app/helpers/house_helper.rb
module HouseHelper
end

kaudee-car/app/helpers/login_helper.rb
module LoginHelper
end

kaudee-car/app/helpers/main_helper.rb
module MainHelper
end

kaudee-car/app/helpers/shop_helper.rb
module ShopHelper
end

kaudee-car/app/helpers/test_helper.rb
module TestHelper
end

kaudee-car/app/helpers/user_helper.rb
module UserHelper
end

kaudee-car/app/views/welcome/index.html.erb
<h1>Kaudee Car</h1>


<h5> * Now Count Cars : <span class='badge'><%= @cars %></span> </h5>

<h5> * Now Count Users : <span class='badge'><%= @users %></span> </h5>

kaudee-car/app/views/welcome/password.html.erb
<!doctype html>
<html>
<head>
  <title>Kaudee Reset Password</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <style>
    html, body{height:100%; margin:0;padding:0}
     
    .container-fluid{
      height:100%;
      display:table;
      width: 100%;
      padding: 0;
    }
     
    .row-fluid {height: 100%; display:table-cell; vertical-align: middle;}
     
     

    .centering {
      float:none;
      margin:0 auto;
    }
  </style>
</head>
<body>
<div class="container-fluid">
  <div class="row-fluid">
    <div class="centering text-center col-md-3">
    <h1>Kaudee</h1>
    <h3>Password Reset</h3>
    <%= form_tag password_resets_path, :method => :post do %>
      <p><input type="text" class="form-control" placeholder="user-mail" name="email" value="<%=params[:email]%>" /></p>
      <p><input type="submit" class="btn btn-success" value="Send Reset Password E-mail" /></p>
    <% end %>
    </div>
  </div>
</div>
</body>

kaudee-car/app/views/welcome/test.html.erb
<!doctype html>
<html>
<head>
<title>test page</title>
</head>
<body>
<h1>Test</h1>

<script>

function test() {
  return "hello";
}
</script>
</body>
</html>