kaudee-car/config/routes.rb
KaudeeCar::Application.routes.draw do
  get 'password_resets/new'

  namespace :api do
    namespace :v1 do
      resources :market
      resources :room
      resources :user
      resources :favorite
      resources :category
      resources :city
      resources :car
      resources :district
      resources :image
      resources :model
      get 'meta' => 'meta#index'
      post 'login' => 'login#index'
    end
  end
end

Rails.application.routes.draw do
  get 'password_resets/new'

  # You can have the root of your site routed with "root"
  root 'welcome#index'
  get 'map/list'
  get 'map/show'
  get 'map/new'
  get 'map/ios'
  get 'welcome/index'
  get 'welcome/policy' => 'welcome#policy'
  get 'welcome/test' => 'welcome#test'
  get 'password' => 'welcome#password'
  post 'login' => 'login#index'
  get 'signout' => 'login#signout'
  get 'market/enable' => 'market#enable'
  get 'market/disable' => 'market#disable'
  get 'admin' => 'user#admin'
  get 'geno' => 'user#geno'

  resources :market
  resources :room
  resources :user
  resources :car
  resources :favorite
  resources :image
  resources :category
  resources :district
  resources :city
  resources :brand
  resources :model
  resources :password_resets
end

kaudee-car/app/models/base.rb
class Base < ActiveRecord::Base
end

kaudee-car/app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :user
  has_many :favorite
end

kaudee-car/app/models/carbrand.rb
class Carbrand < ActiveRecord::Base
has_many  :carmodels
end

kaudee-car/app/models/carmodel.rb
class Carmodel < ActiveRecord::Base
end

kaudee-car/app/models/category.rb
class Category < ActiveRecord::Base
end

kaudee-car/app/models/city.rb
class City < ActiveRecord::Base
  has_many :districts
end

kaudee-car/app/models/district.rb
class District < ActiveRecord::Base
end

kaudee-car/app/models/favorite.rb
class Favorite < ActiveRecord::Base
 validates_uniqueness_of :user_id, :scope => :data_id
end

kaudee-car/app/models/image.rb
class Image < ActiveRecord::Base
	mount_uploader :img, ImageUploader
end

kaudee-car/app/models/market.rb
class Market < ActiveRecord::Base
  belongs_to :user
  has_many :favorite
  #mount_uploader :image, ImageUploader
end

kaudee-car/app/models/room.rb
class Room < ActiveRecord::Base
  #belongs_to :user
  #has_many :favorite
end

kaudee-car/app/models/user.rb
class User < ActiveRecord::Base
  before_create :generate_access_token

  has_many :markets
  validates :email, :password, presence: true
  validates_uniqueness_of :email

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end
  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  private

  def generate_access_token
    begin
      self.access_token = SecureRandom.hex
    end while self.class.exists?(access_token: access_token)
  end
end

kaudee-car/app/controllers/password_resets_controller.rb
class PasswordResetsController < ActionController::Base
  def create
    user = User.find_by_email(params[:email])
    user.send_password_reset if user
    if user
      render json: {:email=>params[:email], :message=>"success"}
    else
      render json: {:message=>"not found"}
    end
  end

  def edit
    @user = User.find_by_password_reset_token!(params[:id])
  end

  def update
    @user = User.find_by_password_reset_token!(params[:id])
    if @user.password_reset_sent_at < 2.hours.ago
      redirect_to new_password_reset_path, :alert => "Password reset has expired."
    elsif params.has_key? (:user) and params[:user][:password] == params[:user][:password_confirmation]
      @user.update(:password=>Digest::MD5.hexdigest(params[:user][:password]))
      #redirect_to root_url, :notice => "Password has been reset!"
      render json: {:message=>"Password has been reset!", :user=>@user[:email]}
    else
      render :edit
    end
  end
end

kaudee-car/app/helpers/car_helper.rb
module CarHelper
end

kaudee-car/app/helpers/home_helper.rb
module HomeHelper
end

kaudee-car/app/helpers/house_helper.rb
module HouseHelper
end

kaudee-car/app/helpers/login_helper.rb
module LoginHelper
end

kaudee-car/app/helpers/main_helper.rb
module MainHelper
end

kaudee-car/app/helpers/shop_helper.rb
module ShopHelper
end

kaudee-car/app/helpers/test_helper.rb
module TestHelper
end

kaudee-car/app/helpers/user_helper.rb
module UserHelper
end

kaudee-car/app/views/password_resets/edit.html.erb
<!doctype html>
<html>
<head>
  <title>Kaudee Reset Password</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <style>
    html, body{height:100%; margin:0;padding:0}
     
    .container-fluid{
      height:100%;
      display:table;
      width: 100%;
      padding: 0;
    }
     
    .row-fluid {height: 100%; display:table-cell; vertical-align: middle;}
     
     

    .centering {
      float:none;
      margin:0 auto;
    }
  </style>
</head>
<body>
<div class="container-fluid">
  <div class="row-fluid">
    <div class="centering text-center col-md-3">
    <h1>Kaudee</h1>
    <h3>Password Reset</h3>
<%= form_for @user, :url => password_reset_path(params[:id]) do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Update Password" %></div>
<% end %>
    </div>
  </div>
</div>
</body>